### ISSUE TITLE
HMIP-WRC2 is not possible to teachin

### ISSUE THREAD

**Issue by christk13** [alexreinert/piVCCU#193] opened 2019-10-08 05:35 UTC
Hello Alex,

my config is Raspi 3B+ with the last pivccu3.
At the teachin procedure the HMIP-WRC2 won't identified.
At an original CCU3 the HMIP-WRC2 is identified immediately.

I look forward that you can help me!
Thx

**Comment by alexreinert** [comment] 2019-10-08 05:56
Please provide the output of pivccu-info.
Did you do a factory reset of the HmIP-WRC2 before teachin?

**Comment by christk13** [comment] 2019-10-08 07:50
For sure factory reset was done.
![image](https://user-images.githubusercontent.com/56289201/66377026-11492400-e9b1-11e9-8518-372ed0540797.png)

**Comment by alexreinert** [comment] 2019-10-08 07:53
Can you provide the log file /var/log/hmserver.log (inside the container)

**Comment by christk13** [comment] 2019-10-08 07:58
with "sudo pivccu-attach cat /var/log/hmserver.log"?

**Comment by alexreinert** [comment] 2019-10-08 08:07
Yes

**Comment by christk13** [comment] 2019-10-08 08:10
[hmserver.txt](https://github.com/alexreinert/piVCCU/files/3701377/hmserver.txt)

**Comment by alexreinert** [comment] 2019-10-08 08:45
There are no errors reported in the log. Your radio module is detected correctly.
Do you have any other HmIP device running inside piVCCU? How do you power the Raspberry?

**Comment by christk13** [comment] 2019-10-08 10:49
The Raspi is powered over the radio module but only with 2A.
1 USB-Stick and 1 WMBus-Stick from Piotek for the SMI260. The WMBus-Stick is connected over an active USB-Ethernet-USB-Extension (Digitus USB-Extender USB2.0).
Sometimes the connection to the HmIP-SWO-PL 00181A498DBE7E is faulty. The Raspi is on the 1st floor and the HmIP-SWO-PL 00181A498DBE7E on the roof.

So it looks like that i have a very strange fault!?

![image](https://user-images.githubusercontent.com/56289201/66389396-98ee5d00-e9c8-11e9-9633-8cd60017621b.png)
![image](https://user-images.githubusercontent.com/56289201/66389433-a60b4c00-e9c8-11e9-9a95-233581308cfe.png)

**Comment by christk13** [comment] 2019-10-09 19:23
Hello Alex,
may i ask you, if you will give further assistance with my problem?
Thx in advance.

**Comment by christk13** [comment] 2019-10-09 21:25
I just saw this information about update?

![image](https://user-images.githubusercontent.com/56289201/66521698-f4653b80-eaeb-11e9-953e-68d646ed84bb.png)

**Comment by alexreinert** [comment] 2019-10-10 06:33
The firmware 3.47.18 was revoked by eQ-3 because of HmIP issue. I don't think, that these issue are the cause of your issues, because there are no error messages in your log.
The HmIP part of the RPI-RF-MOD needs a good power source with a low ripple. You are not using the original power source and use multiple usb devices. This could be the cause of your issue.

**Comment by christk13** [comment] 2019-10-10 07:36
OK, i will buy the original power supply for the RPI-RF-MOD from ELV and then i will post an update.
Do i have to change something with the firmware now, or not?

**Comment by alexreinert** [comment] 2019-10-10 07:44
As I do not have any access to the closed source of the HmIPServer I cannot answer that for sure.

**Comment by christk13** [comment] 2019-10-10 07:57
I will watch the system for any further issues.
Thank you very much.

**Comment by christk13** [comment] 2019-10-10 08:34
The "TP-Link TL-SG1005P" from your wishlist is on the way.
A small present for you project...

**Comment by alexreinert** [comment] 2019-10-10 08:35
Thanks a lot.

**Comment by christk13** [comment] 2019-10-15 20:12
Hi again.
Today i installed the original power source and also a new HMIP-WRC2 from elv.
Sry, but nothing changed - i just have the same problem, that it isn't possible to teachin the WRC2 in any way.
![image](https://user-images.githubusercontent.com/56289201/66863823-22d39280-ef94-11e9-9429-495acc24505a.png)
[hmserver.log.txt](https://github.com/alexreinert/piVCCU/files/3731216/hmserver.log.txt)

Attached also some outputs from CUxD, if they are important:
![image](https://user-images.githubusercontent.com/56289201/66865704-15b8a280-ef98-11e9-845c-dc06f5421a65.png)
[FullSysLogMessages.txt](https://github.com/alexreinert/piVCCU/files/3731232/FullSysLogMessages.txt)
[KernelMessages.txt](https://github.com/alexreinert/piVCCU/files/3731237/KernelMessages.txt)

The Led of the RPI-RF-MOD is yellow flashing with any Systemmessages
![image](https://user-images.githubusercontent.com/56289201/66866031-c4f57980-ef98-11e9-936d-0cc9fd58d81f.png)

May you help me, thx!

**Comment by christk13** [comment] 2019-10-24 21:08
Hello Alex,
today i wanted to update to 3.47.22 with "sudo apt update && sudo apt upgrade", but nothing realy changed.
Attached the actual informations:
![image](https://user-images.githubusercontent.com/56289201/67525155-6d4ec080-f6b2-11e9-8447-728f54bec893.png)
[HMServer_log.txt](https://github.com/alexreinert/piVCCU/files/3769465/HMServer_log.txt)

Pls. provide additional help!

Thank you very much in advance.

**Comment by christk13** [comment] 2019-10-24 21:27
I just tried again to teachin the HMIP-WRC2.
The Led of RPI-RF-MOD was blue before.
Now the Led is flashing yellow.
[HMServer_log_after_teachin.txt]
(https://github.com/alexreinert/piVCCU/files/3769513/HMServer_log_after_teachin.txt)
![image](https://user-images.githubusercontent.com/56289201/67526108-5f01a400-f6b4-11e9-89ea-f73cf11ff1f1.png)

After restarting of the ccu the Led is blue again.
![image](https://user-images.githubusercontent.com/56289201/67526646-81e08800-f6b5-11e9-8fd1-ab710c185d3b.png)
[HMServer_log_after_CCU_restart.txt](https://github.com/alexreinert/piVCCU/files/3769545/HMServer_log_after_CCU_restart.txt)

I hope it is possible to find the failure!

Thanks.

**Comment by alexreinert** [comment] 2019-10-25 03:27
The version 3.47.22 is in the testing apt repo only at the moment. If you edit the file /etc/apt/sources.list.d/debmatic.list you can switch to the testing apt repo and use apt to upgrade afterwards.

**Comment by christk13** [comment] 2019-10-25 05:27
Oh sorry.
How do i know, if it is in stable main?
Have you planned any further actions for my problem with the HMIP-WRC2?
Thx in advance.

**Comment by alexreinert** [comment] 2019-10-25 05:40
If there are no further issues, it will be included in the stable apt repository in about two weeks. But you can of course switch to the testing apt repository right now.
There were change regarding HmIP in the version 3.47.22, but as I have no access to the source code, I cannot confirm, that they will solve your problem, but there are some chances. So please install it, and we will see.

**Comment by christk13** [comment] 2019-10-25 05:55
But i am wondering, because i tested the WRC2 on an original CCU3 and it was taught in immediately.
So i thought it is a problem of your pivccu3-project!?

**Comment by alexreinert** [comment] 2019-10-25 06:10
I don't think so. piVCCU uses the same binaries as the original CCU and the same kernel modules. It is just inside a LXC container.  And as your SWO is working with piVCCU, the issue must be inside the binaries of the CCU firmware or they are hardware related or they are related to an user error.

There were issues regarding HmIP in firmware 3.47.15 and 3.47.18, but they occured just on a bunch of systems. So it is possible, that they are the cause of your issue.

Additionally: You are using a different hardware as the CCU3, which uses a Raspberry 3B (not the 3B+).

And you said, that you did a factory reset of the device. How did you do that? How did you do the teachin exactly?

**Comment by christk13** [comment] 2019-10-25 06:27
Factory reset: exactly according manual
With both methods:
![image](https://user-images.githubusercontent.com/56289201/67547725-2982a800-f700-11e9-8b98-e13ae883f764.png)
I am sure that the teachin procedure is not the problem, because i did it at the original CCU3 in the same way.
But now i understand and for sure i trust in you!
I will try the new firmware.

Thanks a lot for the moment and i will give an update again.

**Comment by christk13** [comment] 2019-10-29 20:09
UPDATE
Today i updated via the testing apt to 3.47.22.
It is still not possible to teachin the HMIP-WRC2.
![image](https://user-images.githubusercontent.com/56289201/67803662-c9885a80-fa8d-11e9-8a03-ad7650f3d564.png)

By the way, what is the meaning of the following error:

pi@raspberrypi:~ $ sudo pivccu-attach cat /var/log/hmserver.log | grep -i erro
Oct 29 20:55:17 de.eq3.cbcs.server.core.vertx.KeyServerWorker ERROR [vert.x-worker-thread-4] Missing key server configuration parameter (Network.Key) for  mode: KEYSERVER_LOCAL
         Oct 29 20:55:17 de.eq3.cbcs.lib.remotecommadapter.device.security.RouterKeyServerWorker ERROR [vert.x-worker-thread-0] Missing key server configuration parameter (Network.Key) for  mode: KEYSERVER_LOCAL
pi@raspberrypi:~ $

[HMServerLog.txt](https://github.com/alexreinert/piVCCU/files/3785591/HMServerLog.txt)

**Comment by alexreinert** [comment] 2019-11-05 09:45
The error in the log is normal behaviour, as there is no predefined key used but the key of the radio module.
Right now I have no idea, what is causing your issue. In all other cases I know, it was either an issue with the power (including issues with power spikes of usb devices), jamming by WLAN/BT/other devices or a wrong teachin procedure.
So, how do you do the teachin? Are you using the system key on the device? If yes, please try an other way: Remove the power source of the device, start the teachin mode in the ccu, repower the device, do not press anything on the device. And of cause, you should remove all of your usb devices for that test.

**Comment by christk13** [comment] 2019-11-09 09:13
With your teachin procedure and without any usb devices the wrc2 was tought in right!
When i reconnect the usb-storage-stick - still everything ok.
But when i reconnect the wmbus-usb-stick, i get a device-communication failure.
So it looks like that this usb device causes the problems.

Alex, do you know, if a usb hub or usb isolator could solve the problem, respectively is it better to connect usb-devices over hubs or isolators in general?

I think the problem is solved for the first-time!

Thank you very much for your support and pivccu-project!!!

**Comment by alexreinert** [comment] 2019-11-09 09:40
In theory, there are 3 different possible issues: All sticks together have a too high current, the wmbus usb stick causes a ripple on the usb bus or the wmbus usb stick causes conflicts on the 868Mhz band.
First and second issue could possible solved by an active usb hub, the last one could possibly solved with some distance.

As I have no wmbus usb stick, I can just speak in theory.

**Closed** 2019-11-09 16:33 UTC
